/*****************************************************************************
 * Copyright 2005 Daniel Ferullo                                             *
 *                                                                           *
 * Licensed under the Apache License, Version 2.0 (the "License");           *
 * you may not use this file except in compliance with the License.          *
 * You may obtain a copy of the License at                                   *
 *                                                                           *
 *    http://www.apache.org/licenses/LICENSE-2.0                             *
 *                                                                           *
 * Unless required by applicable law or agreed to in writing, software       *
 * distributed under the License is distributed on an "AS IS" BASIS,         *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *
 * See the License for the specific language governing permissions and       *
 * limitations under the License.                                            *
 *                                                                           *
 *****************************************************************************/

/**
 * @file errorcodes.h
 * @author Daniel Ferullo (ferullo@cmu.edu)
 *
 * @brief provides some basic general purpose error codes
 *        Autogenerated by gen_err_codes.py on Tue Mar 29 15:16:11 2005
 *
 */


#ifndef __ERRORCODES_H__
#define __ERRORCODES_H__

/** @brief if this is turned on, everytime return ERROR* is called
 * information about the error will be printed to stderr */
#define ERROR_TRACE

#include <stdio.h>

/** @brief a typedef for the errorcode int type return value */
typedef int errorcode;

/** @brief a macro to test for failure */
#define FAILED(x) ((x < SUCCESS) ? 1 : 0)

/** @brief a macro to check for failure and return if failure detected */
#define CHECK_FAILED(x,y) ({ if (FAILED(x)) return y; })

/** @brief ensures the argument is not y, returns errorcode if it is */
#define CHECK_NOT_EQUAL(x,y,z) ({if (x==y) return z;})

/** @brief ensures the argument is not NULL, return error if it is */
#define CHECK_NOT_NULL(x,z) ({if (x==NULL) return z;})

/** @brief ensures the argument is not negative, return error if it is */
#define CHECK_NOT_NEG(x,y) ({if (x<0) return y;})

/** @brief ensures the argument is greater than a given value, returns errorcode if it isn't */
#define CHECK_GREATER_THAN(x,y,z) ({if (x<=y) return z;})



/** @brief Function is finished with it's work */
#define FINISHED 1
		
/** @brief Function was successful */
#define SUCCESS 0
		
/** @brief Function check was OK */
#define OK 0
		
/** @brief Function check was not OK */
#define NOT_OK -1
		
/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR -1
#else
#define ERROR ((fprintf(stderr,"ERROR: General error (ERROR) in %s on line %d\n",__FILE__,__LINE__)==1) ? -1 : -1)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_1 -2
#else
#define ERROR_1 ((fprintf(stderr,"ERROR: General error (ERROR_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -2 : -2)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_2 -3
#else
#define ERROR_2 ((fprintf(stderr,"ERROR: General error (ERROR_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -3 : -3)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_3 -4
#else
#define ERROR_3 ((fprintf(stderr,"ERROR: General error (ERROR_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -4 : -4)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_4 -5
#else
#define ERROR_4 ((fprintf(stderr,"ERROR: General error (ERROR_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -5 : -5)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_5 -6
#else
#define ERROR_5 ((fprintf(stderr,"ERROR: General error (ERROR_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -6 : -6)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_6 -7
#else
#define ERROR_6 ((fprintf(stderr,"ERROR: General error (ERROR_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -7 : -7)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_7 -8
#else
#define ERROR_7 ((fprintf(stderr,"ERROR: General error (ERROR_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -8 : -8)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_8 -9
#else
#define ERROR_8 ((fprintf(stderr,"ERROR: General error (ERROR_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -9 : -9)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_9 -10
#else
#define ERROR_9 ((fprintf(stderr,"ERROR: General error (ERROR_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -10 : -10)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_10 -11
#else
#define ERROR_10 ((fprintf(stderr,"ERROR: General error (ERROR_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -11 : -11)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_11 -12
#else
#define ERROR_11 ((fprintf(stderr,"ERROR: General error (ERROR_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -12 : -12)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_12 -13
#else
#define ERROR_12 ((fprintf(stderr,"ERROR: General error (ERROR_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -13 : -13)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_13 -14
#else
#define ERROR_13 ((fprintf(stderr,"ERROR: General error (ERROR_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -14 : -14)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_14 -15
#else
#define ERROR_14 ((fprintf(stderr,"ERROR: General error (ERROR_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -15 : -15)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_15 -16
#else
#define ERROR_15 ((fprintf(stderr,"ERROR: General error (ERROR_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -16 : -16)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_16 -17
#else
#define ERROR_16 ((fprintf(stderr,"ERROR: General error (ERROR_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -17 : -17)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_17 -18
#else
#define ERROR_17 ((fprintf(stderr,"ERROR: General error (ERROR_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -18 : -18)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_18 -19
#else
#define ERROR_18 ((fprintf(stderr,"ERROR: General error (ERROR_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -19 : -19)
#endif

/** @brief General error */
#ifndef ERROR_TRACE
#define ERROR_19 -20
#else
#define ERROR_19 ((fprintf(stderr,"ERROR: General error (ERROR_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -20 : -20)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG -21
#else
#define ERROR_NULL_ARG ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG) in %s on line %d\n",__FILE__,__LINE__)==1) ? -21 : -21)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_1 -22
#else
#define ERROR_NULL_ARG_1 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -22 : -22)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_2 -23
#else
#define ERROR_NULL_ARG_2 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -23 : -23)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_3 -24
#else
#define ERROR_NULL_ARG_3 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -24 : -24)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_4 -25
#else
#define ERROR_NULL_ARG_4 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -25 : -25)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_5 -26
#else
#define ERROR_NULL_ARG_5 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -26 : -26)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_6 -27
#else
#define ERROR_NULL_ARG_6 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -27 : -27)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_7 -28
#else
#define ERROR_NULL_ARG_7 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -28 : -28)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_8 -29
#else
#define ERROR_NULL_ARG_8 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -29 : -29)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_9 -30
#else
#define ERROR_NULL_ARG_9 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -30 : -30)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_10 -31
#else
#define ERROR_NULL_ARG_10 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -31 : -31)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_11 -32
#else
#define ERROR_NULL_ARG_11 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -32 : -32)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_12 -33
#else
#define ERROR_NULL_ARG_12 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -33 : -33)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_13 -34
#else
#define ERROR_NULL_ARG_13 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -34 : -34)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_14 -35
#else
#define ERROR_NULL_ARG_14 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -35 : -35)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_15 -36
#else
#define ERROR_NULL_ARG_15 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -36 : -36)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_16 -37
#else
#define ERROR_NULL_ARG_16 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -37 : -37)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_17 -38
#else
#define ERROR_NULL_ARG_17 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -38 : -38)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_18 -39
#else
#define ERROR_NULL_ARG_18 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -39 : -39)
#endif

/** @brief A function parameter was illegally NULL */
#ifndef ERROR_TRACE
#define ERROR_NULL_ARG_19 -40
#else
#define ERROR_NULL_ARG_19 ((fprintf(stderr,"ERROR: A function parameter was illegally NULL (ERROR_NULL_ARG_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -40 : -40)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG -41
#else
#define ERROR_NEG_ARG ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG) in %s on line %d\n",__FILE__,__LINE__)==1) ? -41 : -41)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_1 -42
#else
#define ERROR_NEG_ARG_1 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -42 : -42)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_2 -43
#else
#define ERROR_NEG_ARG_2 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -43 : -43)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_3 -44
#else
#define ERROR_NEG_ARG_3 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -44 : -44)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_4 -45
#else
#define ERROR_NEG_ARG_4 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -45 : -45)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_5 -46
#else
#define ERROR_NEG_ARG_5 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -46 : -46)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_6 -47
#else
#define ERROR_NEG_ARG_6 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -47 : -47)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_7 -48
#else
#define ERROR_NEG_ARG_7 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -48 : -48)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_8 -49
#else
#define ERROR_NEG_ARG_8 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -49 : -49)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_9 -50
#else
#define ERROR_NEG_ARG_9 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -50 : -50)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_10 -51
#else
#define ERROR_NEG_ARG_10 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -51 : -51)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_11 -52
#else
#define ERROR_NEG_ARG_11 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -52 : -52)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_12 -53
#else
#define ERROR_NEG_ARG_12 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -53 : -53)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_13 -54
#else
#define ERROR_NEG_ARG_13 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -54 : -54)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_14 -55
#else
#define ERROR_NEG_ARG_14 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -55 : -55)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_15 -56
#else
#define ERROR_NEG_ARG_15 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -56 : -56)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_16 -57
#else
#define ERROR_NEG_ARG_16 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -57 : -57)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_17 -58
#else
#define ERROR_NEG_ARG_17 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -58 : -58)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_18 -59
#else
#define ERROR_NEG_ARG_18 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -59 : -59)
#endif

/** @brief A function parameter was illegally negative */
#ifndef ERROR_TRACE
#define ERROR_NEG_ARG_19 -60
#else
#define ERROR_NEG_ARG_19 ((fprintf(stderr,"ERROR: A function parameter was illegally negative (ERROR_NEG_ARG_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -60 : -60)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG -61
#else
#define ERROR_ARG ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG) in %s on line %d\n",__FILE__,__LINE__)==1) ? -61 : -61)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_1 -62
#else
#define ERROR_ARG_1 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -62 : -62)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_2 -63
#else
#define ERROR_ARG_2 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -63 : -63)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_3 -64
#else
#define ERROR_ARG_3 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -64 : -64)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_4 -65
#else
#define ERROR_ARG_4 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -65 : -65)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_5 -66
#else
#define ERROR_ARG_5 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -66 : -66)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_6 -67
#else
#define ERROR_ARG_6 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -67 : -67)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_7 -68
#else
#define ERROR_ARG_7 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -68 : -68)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_8 -69
#else
#define ERROR_ARG_8 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -69 : -69)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_9 -70
#else
#define ERROR_ARG_9 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -70 : -70)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_10 -71
#else
#define ERROR_ARG_10 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -71 : -71)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_11 -72
#else
#define ERROR_ARG_11 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -72 : -72)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_12 -73
#else
#define ERROR_ARG_12 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -73 : -73)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_13 -74
#else
#define ERROR_ARG_13 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -74 : -74)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_14 -75
#else
#define ERROR_ARG_14 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -75 : -75)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_15 -76
#else
#define ERROR_ARG_15 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -76 : -76)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_16 -77
#else
#define ERROR_ARG_16 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -77 : -77)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_17 -78
#else
#define ERROR_ARG_17 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -78 : -78)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_18 -79
#else
#define ERROR_ARG_18 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -79 : -79)
#endif

/** @brief A function parameter was illegal */
#ifndef ERROR_TRACE
#define ERROR_ARG_19 -80
#else
#define ERROR_ARG_19 ((fprintf(stderr,"ERROR: A function parameter was illegal (ERROR_ARG_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -80 : -80)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE -81
#else
#define ERROR_BUF_SIZE ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE) in %s on line %d\n",__FILE__,__LINE__)==1) ? -81 : -81)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_1 -82
#else
#define ERROR_BUF_SIZE_1 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -82 : -82)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_2 -83
#else
#define ERROR_BUF_SIZE_2 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -83 : -83)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_3 -84
#else
#define ERROR_BUF_SIZE_3 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -84 : -84)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_4 -85
#else
#define ERROR_BUF_SIZE_4 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -85 : -85)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_5 -86
#else
#define ERROR_BUF_SIZE_5 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -86 : -86)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_6 -87
#else
#define ERROR_BUF_SIZE_6 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -87 : -87)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_7 -88
#else
#define ERROR_BUF_SIZE_7 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -88 : -88)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_8 -89
#else
#define ERROR_BUF_SIZE_8 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -89 : -89)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_9 -90
#else
#define ERROR_BUF_SIZE_9 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -90 : -90)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_10 -91
#else
#define ERROR_BUF_SIZE_10 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -91 : -91)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_11 -92
#else
#define ERROR_BUF_SIZE_11 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -92 : -92)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_12 -93
#else
#define ERROR_BUF_SIZE_12 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -93 : -93)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_13 -94
#else
#define ERROR_BUF_SIZE_13 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -94 : -94)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_14 -95
#else
#define ERROR_BUF_SIZE_14 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -95 : -95)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_15 -96
#else
#define ERROR_BUF_SIZE_15 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -96 : -96)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_16 -97
#else
#define ERROR_BUF_SIZE_16 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -97 : -97)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_17 -98
#else
#define ERROR_BUF_SIZE_17 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -98 : -98)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_18 -99
#else
#define ERROR_BUF_SIZE_18 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -99 : -99)
#endif

/** @brief A buffer's size was illegal */
#ifndef ERROR_TRACE
#define ERROR_BUF_SIZE_19 -100
#else
#define ERROR_BUF_SIZE_19 ((fprintf(stderr,"ERROR: A buffer's size was illegal (ERROR_BUF_SIZE_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -100 : -100)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED -101
#else
#define ERROR_MALLOC_FAILED ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED) in %s on line %d\n",__FILE__,__LINE__)==1) ? -101 : -101)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_1 -102
#else
#define ERROR_MALLOC_FAILED_1 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -102 : -102)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_2 -103
#else
#define ERROR_MALLOC_FAILED_2 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -103 : -103)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_3 -104
#else
#define ERROR_MALLOC_FAILED_3 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -104 : -104)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_4 -105
#else
#define ERROR_MALLOC_FAILED_4 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -105 : -105)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_5 -106
#else
#define ERROR_MALLOC_FAILED_5 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -106 : -106)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_6 -107
#else
#define ERROR_MALLOC_FAILED_6 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -107 : -107)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_7 -108
#else
#define ERROR_MALLOC_FAILED_7 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -108 : -108)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_8 -109
#else
#define ERROR_MALLOC_FAILED_8 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -109 : -109)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_9 -110
#else
#define ERROR_MALLOC_FAILED_9 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -110 : -110)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_10 -111
#else
#define ERROR_MALLOC_FAILED_10 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -111 : -111)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_11 -112
#else
#define ERROR_MALLOC_FAILED_11 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -112 : -112)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_12 -113
#else
#define ERROR_MALLOC_FAILED_12 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -113 : -113)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_13 -114
#else
#define ERROR_MALLOC_FAILED_13 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -114 : -114)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_14 -115
#else
#define ERROR_MALLOC_FAILED_14 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -115 : -115)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_15 -116
#else
#define ERROR_MALLOC_FAILED_15 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -116 : -116)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_16 -117
#else
#define ERROR_MALLOC_FAILED_16 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -117 : -117)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_17 -118
#else
#define ERROR_MALLOC_FAILED_17 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -118 : -118)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_18 -119
#else
#define ERROR_MALLOC_FAILED_18 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -119 : -119)
#endif

/** @brief Malloc failed */
#ifndef ERROR_TRACE
#define ERROR_MALLOC_FAILED_19 -120
#else
#define ERROR_MALLOC_FAILED_19 ((fprintf(stderr,"ERROR: Malloc failed (ERROR_MALLOC_FAILED_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -120 : -120)
#endif

/** @brief A socket couldn't be created */
#ifndef ERROR_TRACE
#define ERROR_SOCKET_CREATE -121
#else
#define ERROR_SOCKET_CREATE ((fprintf(stderr,"ERROR: A socket couldn't be created (ERROR_SOCKET_CREATE) in %s on line %d\n",__FILE__,__LINE__)==1) ? -121 : -121)
#endif

/** @brief A port couldn't be bound to */
#ifndef ERROR_TRACE
#define ERROR_BIND -122
#else
#define ERROR_BIND ((fprintf(stderr,"ERROR: A port couldn't be bound to (ERROR_BIND) in %s on line %d\n",__FILE__,__LINE__)==1) ? -122 : -122)
#endif

/** @brief A TCP connection failed */
#ifndef ERROR_TRACE
#define ERROR_TCP_CONNECT -123
#else
#define ERROR_TCP_CONNECT ((fprintf(stderr,"ERROR: A TCP connection failed (ERROR_TCP_CONNECT) in %s on line %d\n",__FILE__,__LINE__)==1) ? -123 : -123)
#endif

/** @brief A TCP connection was closed */
#ifndef ERROR_TRACE
#define ERROR_TCP_CLOSED -124
#else
#define ERROR_TCP_CLOSED ((fprintf(stderr,"ERROR: A TCP connection was closed (ERROR_TCP_CLOSED) in %s on line %d\n",__FILE__,__LINE__)==1) ? -124 : -124)
#endif

/** @brief A TCP receive failed */
#ifndef ERROR_TRACE
#define ERROR_TCP_RECEIVE -125
#else
#define ERROR_TCP_RECEIVE ((fprintf(stderr,"ERROR: A TCP receive failed (ERROR_TCP_RECEIVE) in %s on line %d\n",__FILE__,__LINE__)==1) ? -125 : -125)
#endif

/** @brief A TCP send failed */
#ifndef ERROR_TRACE
#define ERROR_TCP_SEND -126
#else
#define ERROR_TCP_SEND ((fprintf(stderr,"ERROR: A TCP send failed (ERROR_TCP_SEND) in %s on line %d\n",__FILE__,__LINE__)==1) ? -126 : -126)
#endif

/** @brief A TCP read failed */
#ifndef ERROR_TRACE
#define ERROR_TCP_READ -127
#else
#define ERROR_TCP_READ ((fprintf(stderr,"ERROR: A TCP read failed (ERROR_TCP_READ) in %s on line %d\n",__FILE__,__LINE__)==1) ? -127 : -127)
#endif

/** @brief A TCP write failed */
#ifndef ERROR_TRACE
#define ERROR_TCP_WRITE -128
#else
#define ERROR_TCP_WRITE ((fprintf(stderr,"ERROR: A TCP write failed (ERROR_TCP_WRITE) in %s on line %d\n",__FILE__,__LINE__)==1) ? -128 : -128)
#endif

/** @brief A pthread creation failed */
#ifndef ERROR_TRACE
#define ERROR_PTHREAD_CREATE_FAILED -129
#else
#define ERROR_PTHREAD_CREATE_FAILED ((fprintf(stderr,"ERROR: A pthread creation failed (ERROR_PTHREAD_CREATE_FAILED) in %s on line %d\n",__FILE__,__LINE__)==1) ? -129 : -129)
#endif

/** @brief A pthread detach failed */
#ifndef ERROR_TRACE
#define ERROR_PTHREAD_DETACH_FAILED -130
#else
#define ERROR_PTHREAD_DETACH_FAILED ((fprintf(stderr,"ERROR: A pthread detach failed (ERROR_PTHREAD_DETACH_FAILED) in %s on line %d\n",__FILE__,__LINE__)==1) ? -130 : -130)
#endif

/** @brief A mutex unlock call failed */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_FAILED -131
#else
#define ERROR_MUTEX_UNLOCK_FAILED ((fprintf(stderr,"ERROR: A mutex unlock call failed (ERROR_MUTEX_UNLOCK_FAILED) in %s on line %d\n",__FILE__,__LINE__)==1) ? -131 : -131)
#endif

/** @brief A device could not be found */
#ifndef ERROR_TRACE
#define ERROR_NO_DEV_FOUND -132
#else
#define ERROR_NO_DEV_FOUND ((fprintf(stderr,"ERROR: A device could not be found (ERROR_NO_DEV_FOUND) in %s on line %d\n",__FILE__,__LINE__)==1) ? -132 : -132)
#endif

/** @brief When searching for an item it was not found */
#ifndef ERROR_TRACE
#define ERROR_NOT_FOUND -133
#else
#define ERROR_NOT_FOUND ((fprintf(stderr,"ERROR: When searching for an item it was not found (ERROR_NOT_FOUND) in %s on line %d\n",__FILE__,__LINE__)==1) ? -133 : -133)
#endif

/** @brief A function called through a function pointer failed */
#ifndef ERROR_TRACE
#define ERROR_FUNC_POINTER_FUNC_FAILED -134
#else
#define ERROR_FUNC_POINTER_FUNC_FAILED ((fprintf(stderr,"ERROR: A function called through a function pointer failed (ERROR_FUNC_POINTER_FUNC_FAILED) in %s on line %d\n",__FILE__,__LINE__)==1) ? -134 : -134)
#endif

/** @brief A function called through a function pointer was invalid */
#ifndef ERROR_TRACE
#define ERROR_FUNC_POINTER_FUNC_INVALID -135
#else
#define ERROR_FUNC_POINTER_FUNC_INVALID ((fprintf(stderr,"ERROR: A function called through a function pointer was invalid (ERROR_FUNC_POINTER_FUNC_INVALID) in %s on line %d\n",__FILE__,__LINE__)==1) ? -135 : -135)
#endif

/** @brief A file could not be opened */
#ifndef ERROR_TRACE
#define ERROR_FILE_OPEN -136
#else
#define ERROR_FILE_OPEN ((fprintf(stderr,"ERROR: A file could not be opened (ERROR_FILE_OPEN) in %s on line %d\n",__FILE__,__LINE__)==1) ? -136 : -136)
#endif

/** @brief A file could not be opened for appending */
#ifndef ERROR_TRACE
#define ERROR_FILE_OPEN_APPEND -137
#else
#define ERROR_FILE_OPEN_APPEND ((fprintf(stderr,"ERROR: A file could not be opened for appending (ERROR_FILE_OPEN_APPEND) in %s on line %d\n",__FILE__,__LINE__)==1) ? -137 : -137)
#endif

/** @brief There was an error while parsing an XML document */
#ifndef ERROR_TRACE
#define ERROR_XML_PARSE -138
#else
#define ERROR_XML_PARSE ((fprintf(stderr,"ERROR: There was an error while parsing an XML document (ERROR_XML_PARSE) in %s on line %d\n",__FILE__,__LINE__)==1) ? -138 : -138)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT -139
#else
#define ERROR_OUTPUT ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT) in %s on line %d\n",__FILE__,__LINE__)==1) ? -139 : -139)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_1 -140
#else
#define ERROR_OUTPUT_1 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -140 : -140)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_2 -141
#else
#define ERROR_OUTPUT_2 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -141 : -141)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_3 -142
#else
#define ERROR_OUTPUT_3 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -142 : -142)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_4 -143
#else
#define ERROR_OUTPUT_4 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -143 : -143)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_5 -144
#else
#define ERROR_OUTPUT_5 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -144 : -144)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_6 -145
#else
#define ERROR_OUTPUT_6 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -145 : -145)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_7 -146
#else
#define ERROR_OUTPUT_7 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -146 : -146)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_8 -147
#else
#define ERROR_OUTPUT_8 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -147 : -147)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_9 -148
#else
#define ERROR_OUTPUT_9 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -148 : -148)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_10 -149
#else
#define ERROR_OUTPUT_10 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -149 : -149)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_11 -150
#else
#define ERROR_OUTPUT_11 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -150 : -150)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_12 -151
#else
#define ERROR_OUTPUT_12 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -151 : -151)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_13 -152
#else
#define ERROR_OUTPUT_13 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -152 : -152)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_14 -153
#else
#define ERROR_OUTPUT_14 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -153 : -153)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_15 -154
#else
#define ERROR_OUTPUT_15 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -154 : -154)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_16 -155
#else
#define ERROR_OUTPUT_16 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -155 : -155)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_17 -156
#else
#define ERROR_OUTPUT_17 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -156 : -156)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_18 -157
#else
#define ERROR_OUTPUT_18 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -157 : -157)
#endif

/** @brief There was an error when attempting to output data */
#ifndef ERROR_TRACE
#define ERROR_OUTPUT_19 -158
#else
#define ERROR_OUTPUT_19 ((fprintf(stderr,"ERROR: There was an error when attempting to output data (ERROR_OUTPUT_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -158 : -158)
#endif

/** @brief A lookup of a hostname failed */
#ifndef ERROR_TRACE
#define ERROR_HOST_NAME_LOOKUP -159
#else
#define ERROR_HOST_NAME_LOOKUP ((fprintf(stderr,"ERROR: A lookup of a hostname failed (ERROR_HOST_NAME_LOOKUP) in %s on line %d\n",__FILE__,__LINE__)==1) ? -159 : -159)
#endif

/** @brief A TCP listen call failed */
#ifndef ERROR_TRACE
#define ERROR_TCP_LISTEN -160
#else
#define ERROR_TCP_LISTEN ((fprintf(stderr,"ERROR: A TCP listen call failed (ERROR_TCP_LISTEN) in %s on line %d\n",__FILE__,__LINE__)==1) ? -160 : -160)
#endif

/** @brief A TCP socket call failed */
#ifndef ERROR_TRACE
#define ERROR_TCP_SOCKET -161
#else
#define ERROR_TCP_SOCKET ((fprintf(stderr,"ERROR: A TCP socket call failed (ERROR_TCP_SOCKET) in %s on line %d\n",__FILE__,__LINE__)==1) ? -161 : -161)
#endif

/** @brief Initialization failed */
#ifndef ERROR_TRACE
#define ERROR_INIT -162
#else
#define ERROR_INIT ((fprintf(stderr,"ERROR: Initialization failed (ERROR_INIT) in %s on line %d\n",__FILE__,__LINE__)==1) ? -162 : -162)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK -163
#else
#define ERROR_MUTEX_LOCK ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK) in %s on line %d\n",__FILE__,__LINE__)==1) ? -163 : -163)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_1 -164
#else
#define ERROR_MUTEX_LOCK_1 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -164 : -164)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_2 -165
#else
#define ERROR_MUTEX_LOCK_2 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -165 : -165)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_3 -166
#else
#define ERROR_MUTEX_LOCK_3 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -166 : -166)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_4 -167
#else
#define ERROR_MUTEX_LOCK_4 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -167 : -167)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_5 -168
#else
#define ERROR_MUTEX_LOCK_5 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -168 : -168)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_6 -169
#else
#define ERROR_MUTEX_LOCK_6 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -169 : -169)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_7 -170
#else
#define ERROR_MUTEX_LOCK_7 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -170 : -170)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_8 -171
#else
#define ERROR_MUTEX_LOCK_8 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -171 : -171)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_9 -172
#else
#define ERROR_MUTEX_LOCK_9 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -172 : -172)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_10 -173
#else
#define ERROR_MUTEX_LOCK_10 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -173 : -173)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_11 -174
#else
#define ERROR_MUTEX_LOCK_11 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -174 : -174)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_12 -175
#else
#define ERROR_MUTEX_LOCK_12 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -175 : -175)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_13 -176
#else
#define ERROR_MUTEX_LOCK_13 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -176 : -176)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_14 -177
#else
#define ERROR_MUTEX_LOCK_14 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -177 : -177)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_15 -178
#else
#define ERROR_MUTEX_LOCK_15 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -178 : -178)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_16 -179
#else
#define ERROR_MUTEX_LOCK_16 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -179 : -179)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_17 -180
#else
#define ERROR_MUTEX_LOCK_17 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -180 : -180)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_18 -181
#else
#define ERROR_MUTEX_LOCK_18 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -181 : -181)
#endif

/** @brief A mutex could not be locked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_LOCK_19 -182
#else
#define ERROR_MUTEX_LOCK_19 ((fprintf(stderr,"ERROR: A mutex could not be locked (ERROR_MUTEX_LOCK_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -182 : -182)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK -183
#else
#define ERROR_MUTEX_UNLOCK ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK) in %s on line %d\n",__FILE__,__LINE__)==1) ? -183 : -183)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_1 -184
#else
#define ERROR_MUTEX_UNLOCK_1 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -184 : -184)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_2 -185
#else
#define ERROR_MUTEX_UNLOCK_2 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -185 : -185)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_3 -186
#else
#define ERROR_MUTEX_UNLOCK_3 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -186 : -186)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_4 -187
#else
#define ERROR_MUTEX_UNLOCK_4 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -187 : -187)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_5 -188
#else
#define ERROR_MUTEX_UNLOCK_5 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -188 : -188)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_6 -189
#else
#define ERROR_MUTEX_UNLOCK_6 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -189 : -189)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_7 -190
#else
#define ERROR_MUTEX_UNLOCK_7 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -190 : -190)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_8 -191
#else
#define ERROR_MUTEX_UNLOCK_8 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -191 : -191)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_9 -192
#else
#define ERROR_MUTEX_UNLOCK_9 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -192 : -192)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_10 -193
#else
#define ERROR_MUTEX_UNLOCK_10 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -193 : -193)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_11 -194
#else
#define ERROR_MUTEX_UNLOCK_11 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -194 : -194)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_12 -195
#else
#define ERROR_MUTEX_UNLOCK_12 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -195 : -195)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_13 -196
#else
#define ERROR_MUTEX_UNLOCK_13 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -196 : -196)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_14 -197
#else
#define ERROR_MUTEX_UNLOCK_14 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -197 : -197)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_15 -198
#else
#define ERROR_MUTEX_UNLOCK_15 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -198 : -198)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_16 -199
#else
#define ERROR_MUTEX_UNLOCK_16 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -199 : -199)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_17 -200
#else
#define ERROR_MUTEX_UNLOCK_17 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -200 : -200)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_18 -201
#else
#define ERROR_MUTEX_UNLOCK_18 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -201 : -201)
#endif

/** @brief A mutex couild not be unlocked */
#ifndef ERROR_TRACE
#define ERROR_MUTEX_UNLOCK_19 -202
#else
#define ERROR_MUTEX_UNLOCK_19 ((fprintf(stderr,"ERROR: A mutex couild not be unlocked (ERROR_MUTEX_UNLOCK_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -202 : -202)
#endif

/** @brief An error occured when trying to add to a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_ADD -203
#else
#define ERROR_LIST_ADD ((fprintf(stderr,"ERROR: An error occured when trying to add to a list (ERROR_LIST_ADD) in %s on line %d\n",__FILE__,__LINE__)==1) ? -203 : -203)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE -204
#else
#define ERROR_LIST_REMOVE ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE) in %s on line %d\n",__FILE__,__LINE__)==1) ? -204 : -204)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_1 -205
#else
#define ERROR_LIST_REMOVE_1 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -205 : -205)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_2 -206
#else
#define ERROR_LIST_REMOVE_2 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -206 : -206)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_3 -207
#else
#define ERROR_LIST_REMOVE_3 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -207 : -207)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_4 -208
#else
#define ERROR_LIST_REMOVE_4 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -208 : -208)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_5 -209
#else
#define ERROR_LIST_REMOVE_5 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -209 : -209)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_6 -210
#else
#define ERROR_LIST_REMOVE_6 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -210 : -210)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_7 -211
#else
#define ERROR_LIST_REMOVE_7 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -211 : -211)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_8 -212
#else
#define ERROR_LIST_REMOVE_8 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -212 : -212)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_9 -213
#else
#define ERROR_LIST_REMOVE_9 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -213 : -213)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_10 -214
#else
#define ERROR_LIST_REMOVE_10 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -214 : -214)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_11 -215
#else
#define ERROR_LIST_REMOVE_11 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -215 : -215)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_12 -216
#else
#define ERROR_LIST_REMOVE_12 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -216 : -216)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_13 -217
#else
#define ERROR_LIST_REMOVE_13 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -217 : -217)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_14 -218
#else
#define ERROR_LIST_REMOVE_14 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -218 : -218)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_15 -219
#else
#define ERROR_LIST_REMOVE_15 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -219 : -219)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_16 -220
#else
#define ERROR_LIST_REMOVE_16 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -220 : -220)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_17 -221
#else
#define ERROR_LIST_REMOVE_17 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -221 : -221)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_18 -222
#else
#define ERROR_LIST_REMOVE_18 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -222 : -222)
#endif

/** @brief An error occured when trying to remove from a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_REMOVE_19 -223
#else
#define ERROR_LIST_REMOVE_19 ((fprintf(stderr,"ERROR: An error occured when trying to remove from a list (ERROR_LIST_REMOVE_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -223 : -223)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND -224
#else
#define ERROR_LIST_FIND ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND) in %s on line %d\n",__FILE__,__LINE__)==1) ? -224 : -224)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_1 -225
#else
#define ERROR_LIST_FIND_1 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -225 : -225)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_2 -226
#else
#define ERROR_LIST_FIND_2 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -226 : -226)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_3 -227
#else
#define ERROR_LIST_FIND_3 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -227 : -227)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_4 -228
#else
#define ERROR_LIST_FIND_4 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -228 : -228)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_5 -229
#else
#define ERROR_LIST_FIND_5 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -229 : -229)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_6 -230
#else
#define ERROR_LIST_FIND_6 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -230 : -230)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_7 -231
#else
#define ERROR_LIST_FIND_7 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -231 : -231)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_8 -232
#else
#define ERROR_LIST_FIND_8 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -232 : -232)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_9 -233
#else
#define ERROR_LIST_FIND_9 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -233 : -233)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_10 -234
#else
#define ERROR_LIST_FIND_10 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -234 : -234)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_11 -235
#else
#define ERROR_LIST_FIND_11 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -235 : -235)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_12 -236
#else
#define ERROR_LIST_FIND_12 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -236 : -236)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_13 -237
#else
#define ERROR_LIST_FIND_13 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -237 : -237)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_14 -238
#else
#define ERROR_LIST_FIND_14 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -238 : -238)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_15 -239
#else
#define ERROR_LIST_FIND_15 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -239 : -239)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_16 -240
#else
#define ERROR_LIST_FIND_16 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -240 : -240)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_17 -241
#else
#define ERROR_LIST_FIND_17 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -241 : -241)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_18 -242
#else
#define ERROR_LIST_FIND_18 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -242 : -242)
#endif

/** @brief An error occured when trying to find an item in a list */
#ifndef ERROR_TRACE
#define ERROR_LIST_FIND_19 -243
#else
#define ERROR_LIST_FIND_19 ((fprintf(stderr,"ERROR: An error occured when trying to find an item in a list (ERROR_LIST_FIND_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -243 : -243)
#endif

/** @brief An error occured when trying to read from the network */
#ifndef ERROR_TRACE
#define ERROR_NETWORK_READ -244
#else
#define ERROR_NETWORK_READ ((fprintf(stderr,"ERROR: An error occured when trying to read from the network (ERROR_NETWORK_READ) in %s on line %d\n",__FILE__,__LINE__)==1) ? -244 : -244)
#endif

/** @brief An error occured when trying to send on the network */
#ifndef ERROR_TRACE
#define ERROR_NETWORK_SEND -245
#else
#define ERROR_NETWORK_SEND ((fprintf(stderr,"ERROR: An error occured when trying to send on the network (ERROR_NETWORK_SEND) in %s on line %d\n",__FILE__,__LINE__)==1) ? -245 : -245)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION -246
#else
#define ERROR_CALLED_FUNCTION ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION) in %s on line %d\n",__FILE__,__LINE__)==1) ? -246 : -246)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_1 -247
#else
#define ERROR_CALLED_FUNCTION_1 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_1) in %s on line %d\n",__FILE__,__LINE__)==1) ? -247 : -247)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_2 -248
#else
#define ERROR_CALLED_FUNCTION_2 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_2) in %s on line %d\n",__FILE__,__LINE__)==1) ? -248 : -248)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_3 -249
#else
#define ERROR_CALLED_FUNCTION_3 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_3) in %s on line %d\n",__FILE__,__LINE__)==1) ? -249 : -249)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_4 -250
#else
#define ERROR_CALLED_FUNCTION_4 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_4) in %s on line %d\n",__FILE__,__LINE__)==1) ? -250 : -250)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_5 -251
#else
#define ERROR_CALLED_FUNCTION_5 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_5) in %s on line %d\n",__FILE__,__LINE__)==1) ? -251 : -251)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_6 -252
#else
#define ERROR_CALLED_FUNCTION_6 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_6) in %s on line %d\n",__FILE__,__LINE__)==1) ? -252 : -252)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_7 -253
#else
#define ERROR_CALLED_FUNCTION_7 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_7) in %s on line %d\n",__FILE__,__LINE__)==1) ? -253 : -253)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_8 -254
#else
#define ERROR_CALLED_FUNCTION_8 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_8) in %s on line %d\n",__FILE__,__LINE__)==1) ? -254 : -254)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_9 -255
#else
#define ERROR_CALLED_FUNCTION_9 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_9) in %s on line %d\n",__FILE__,__LINE__)==1) ? -255 : -255)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_10 -256
#else
#define ERROR_CALLED_FUNCTION_10 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_10) in %s on line %d\n",__FILE__,__LINE__)==1) ? -256 : -256)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_11 -257
#else
#define ERROR_CALLED_FUNCTION_11 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_11) in %s on line %d\n",__FILE__,__LINE__)==1) ? -257 : -257)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_12 -258
#else
#define ERROR_CALLED_FUNCTION_12 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_12) in %s on line %d\n",__FILE__,__LINE__)==1) ? -258 : -258)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_13 -259
#else
#define ERROR_CALLED_FUNCTION_13 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_13) in %s on line %d\n",__FILE__,__LINE__)==1) ? -259 : -259)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_14 -260
#else
#define ERROR_CALLED_FUNCTION_14 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_14) in %s on line %d\n",__FILE__,__LINE__)==1) ? -260 : -260)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_15 -261
#else
#define ERROR_CALLED_FUNCTION_15 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_15) in %s on line %d\n",__FILE__,__LINE__)==1) ? -261 : -261)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_16 -262
#else
#define ERROR_CALLED_FUNCTION_16 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_16) in %s on line %d\n",__FILE__,__LINE__)==1) ? -262 : -262)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_17 -263
#else
#define ERROR_CALLED_FUNCTION_17 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_17) in %s on line %d\n",__FILE__,__LINE__)==1) ? -263 : -263)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_18 -264
#else
#define ERROR_CALLED_FUNCTION_18 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_18) in %s on line %d\n",__FILE__,__LINE__)==1) ? -264 : -264)
#endif

/** @brief An error occured in a called function */
#ifndef ERROR_TRACE
#define ERROR_CALLED_FUNCTION_19 -265
#else
#define ERROR_CALLED_FUNCTION_19 ((fprintf(stderr,"ERROR: An error occured in a called function (ERROR_CALLED_FUNCTION_19) in %s on line %d\n",__FILE__,__LINE__)==1) ? -265 : -265)
#endif

/** @brief A timeout occured */
#ifndef ERROR_TRACE
#define ERROR_TIMEOUT -266
#else
#define ERROR_TIMEOUT ((fprintf(stderr,"ERROR: A timeout occured (ERROR_TIMEOUT) in %s on line %d\n",__FILE__,__LINE__)==1) ? -266 : -266)
#endif

/** @brief A pthread_join call failed */
#ifndef ERROR_TRACE
#define ERROR_PTHREAD_JOIN -267
#else
#define ERROR_PTHREAD_JOIN ((fprintf(stderr,"ERROR: A pthread_join call failed (ERROR_PTHREAD_JOIN) in %s on line %d\n",__FILE__,__LINE__)==1) ? -267 : -267)
#endif

/** @brief An array access was out of bounds */
#ifndef ERROR_TRACE
#define ERROR_OUT_OF_BOUNDS -268
#else
#define ERROR_OUT_OF_BOUNDS ((fprintf(stderr,"ERROR: An array access was out of bounds (ERROR_OUT_OF_BOUNDS) in %s on line %d\n",__FILE__,__LINE__)==1) ? -268 : -268)
#endif

/** @brief The new operator failed to allocate new memory */
#ifndef ERROR_TRACE
#define ERROR_NEW_FAILED -269
#else
#define ERROR_NEW_FAILED ((fprintf(stderr,"ERROR: The new operator failed to allocate new memory (ERROR_NEW_FAILED) in %s on line %d\n",__FILE__,__LINE__)==1) ? -269 : -269)
#endif

#endif /* __ERRORCODES_H__ */
